apps/views/article.py
from flask import Blueprint, flash, request, redirect, render_template, url_for,jsonify
from flask_login import login_required,current_user
from sqlalchemy import and_, or_

from apps.models.ariticle import Article_type, Article, Comment, Like, Favorite
from exts import db
from exts.like import del_like, get_like, get_favorite, del_favorite

article_bp = Blueprint('article_bp',__name__,url_prefix='/article')#创建蓝图

#添加文章类型
@article_bp.route('/add_type',methods=['GET','POST'])
def add_type():
    types = Article_type.query.all()
    if request.method == 'POST':
        type = request.form.get('type')
        article_type = Article_type()
        article_type.type = type
        db.session.add(article_type)
        db.session.commit()
        flash('文章类型添加成功')
        return redirect(url_for('article_bp.show_type'))
    return render_template('article/add_type.html',types=types)


#修改文章类型
@article_bp.route('/modify_type',methods=['GET','POST'])
def modify_type():
    types = Article_type.query.all()
    if request.method == 'POST':
        tid = request.form.get('tid')
        type = request.form.get('type')
        article_type = Article_type.query.get(tid)
        article_type.type = type
        db.session.commit()
        flash('类型修改成功')
        return redirect(url_for('article_bp.show_type'))
    tid = request.args.get('tid')
    article_type = Article_type.query.get(tid)
    return render_template('article/modify_type.html',article_type=article_type,types=types)



#删除文章类型
@article_bp.route('/del_type',methods=['GET','POST'])
def del_type():
    tid = request.args.get('tid')
    article_type = Article_type.query.get(tid)
    db.session.delete(article_type)
    db.session.commit()
    flash('类型删除成功')
    return redirect(url_for('article_bp.show_type'))


#显示文章类型
@article_bp.route('show_type',methods=['GET','POST'])
def show_type():
    types= Article_type.query.all()
    return render_template('article/show_type.html',types=types)


#文章发布
@article_bp.route('/publish',methods=['GET','POST'])
@login_required
def publish():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        type_id = request.form.get('type_id')
        article = Article()
        article.title = title
        article.content = content
        article.type_id = type_id
        article.user_id = current_user.id
        db.session.add(article)
        db.session.commit()
        flash('文章发布成功')
        return redirect(url_for('user_bp.index'))
    types = Article_type.query.all()
    return render_template('article/publish_article.html',types=types)


#文章详情页
@article_bp.route('/details',methods=['GET','POST'])
def details():
    types = Article_type.query.all()
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id==aid).first()
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.filter(Comment.article_id == aid).order_by(Comment.datetime.desc()).paginate(page=page, per_page=5, error_out=False)
    return render_template('article/details.html',article=article,pagination=pagination,types=types)



#发布评论
@article_bp.route('/comment',methods=['GET','POST'])
@login_required
def comment():
    types = Article_type.query.all()
    aid = request.form.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    c_content = request.form.get('c_content')
    comment = Comment()
    comment.content = c_content
    comment.article_id = aid
    comment.user_id = current_user.id
    db.session.add(comment)
    db.session.commit()
    page = request.args.get('page',1,type=int)
    pagination = Comment.query.filter(Comment.article_id == aid).order_by(Comment.datetime.desc()).paginate(page=page,per_page=5,error_out=False)
    flash('评论成功')
    return render_template('article/details.html',article=article,pagination=pagination,types=types)



#点赞实现
@article_bp.route('/like',methods=['GET','POST'])
@login_required
def like():
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    if Like.is_like(aid):#判断是否已经点赞
        del_like(aid)#取消点赞
    else:
        get_like(aid)#增加点赞
    db.session.commit()
    return jsonify(num=article.like)



#收藏实现
@article_bp.route('/favorite',methods=['GET','POST'])
@login_required
def favorite():
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    if Favorite.is_favorite(aid):#判断是否已经收藏
        del_favorite(aid)#取消收藏
    else:
        get_favorite(aid)#增加收藏
    db.session.commit()
    return jsonify(num=article.Favorites)


#显示评论
@article_bp.route('/show_comment',methods=['GET','POST'])
@login_required
def show_comment():
    types = Article_type.query.all()
    page = request.args.get('page',1,type=int)
    pagination = Comment.query.filter(Comment.user_id==current_user.id)\
        .order_by(Comment.datetime.desc()).paginate(page=page,per_page=5,error_out=False)
    return render_template('comment/show_comment.html',pagination=pagination,types=types)


#删除评论
@article_bp.route('/del_comment/',methods=['GET','POST'])
@login_required
def del_comment_11():
    cid = request.args.get('cid')
    comment = Comment.query.filter(Comment.id==cid).first()
    if comment:
        db.session.delete(comment)
        db.session.commit()
        flash('评论删除成功')
    else:
        flash('该评论不存在')
    return redirect(url_for('article_bp.show_comment'))


#文章分类显示
@article_bp.route('/article_class_show/',methods=['GET','POST'])
@login_required
def article_class_show():
    types = Article_type.query.all()
    tid = request.args.get('tid')
    page = request.args.get('page',1,type=int)
    pagination = Article.query.filter(Article.type_id==tid).paginate(page=page,per_page=5,error_out=False)
    return render_template('article/article.html',pagination=pagination,types=types,tid=tid)


#显示当前用户的文章
@article_bp.route('/show_user_article/',methods=['GET','POST'])
@login_required
def show_user_article():
    types = Article_type.query.all()
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.filter(Article.user_id==current_user.id).paginate(page=page,per_page=5,error_out=False)
    return render_template('article/show_user_article.html',pagination=pagination,types=types)



#修改文章
@article_bp.route('/modify_article/',methods=['GET','POST'])
@login_required
def modify_article():
    if request.method == 'POST':
        aid = request.form.get('aid')
        title = request.form.get('title')
        content = request.form.get('content')
        article = Article.query.filter(Article.id==aid).first()
        article.title=title
        article.content=content
        db.session.commit()
        flash('文章修改成功')
        return redirect(url_for('article_bp.show_user_article'))
    types = Article_type.query.all()
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id==aid).first()
    return render_template('article/modify_article.html',article=article,types=types)

#删除文章
@article_bp.route('/del_article/',methods=['GET','POST'])
@login_required
def del_article():
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    db.session.delete(article)
    db.session.commit()
    flash('文章删除成功')
    return redirect(url_for('article_bp.show_user_article'))


#通过关键词搜索文章
@article_bp.route('/search/',methods=['GET','POST'])
def search():
    types = Article_type.query.all()
    keyword = request.form.get('search')
    page = request.args.get('page',1,type=int)
    pagination = Article.query.filter(Article.title.contains(keyword)).paginate(page=page,per_page=5,error_out=False)
    if not pagination.items:
        flash('没有您要找的相关文章')
    return render_template('article/search_article.html', pagination=pagination, types=types)

apps/views/user.py
import os
import random
from io import BytesIO


from flask_login import login_user,current_user,logout_user,login_required
from flask import Blueprint, render_template, request, flash, make_response, redirect, url_for

from werkzeug.security import generate_password_hash, check_password_hash

from apps.models.ariticle import Article, Article_type, Message
from apps.models.user import User, Personal_information
from config import Baseconfig
from exts import db, cache, photos
from exts.captcha import generate_captcha
from exts.mail_send import send_mail

user_bp = Blueprint('user_bp',__name__,url_prefix='/user')#创建蓝图


#首页
@user_bp.route('/index')
def index():
    types = Article_type.query.all()
    page = request.args.get('page',1,type=int)
    pagination = Article.query.paginate(page=page,per_page=5,error_out=False)
    return render_template('index.html',pagination=pagination,types=types)


#把验证码返回到前端页面
@user_bp.route('/captcha_show')
def captcha_show():
    im,code = generate_captcha(4)
    cache.set('cc',code,timeout=180)#把code存入redis
    buffer = BytesIO()#创建缓存对象,以二进制的形式存储
    im.save(buffer,'JPEG')#存入缓存
    image = buffer.getvalue()#得到图片
    response = make_response(image)#自定义response
    response.headers['Content-Type'] = 'image/jpg'#设置响应头
    return response


#注册
@user_bp.route('/register',methods=['GET','POST'])
def register():
    types = Article_type.query.all()
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        email = request.form.get('email')
        phone = request.form.get('phone')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        if password != repassword:
            flash('您输入的两次密码不一致')
            return redirect(url_for('user_bp.register'))
        if captcha != new_captcha:
            flash('您输入的验证码有误')
            return redirect(url_for('user_bp.register'))
        #把数据写入数据库
        user = User()
        user.username = username
        user.password = generate_password_hash(password)
        user.email = email
        user.phone = phone
        db.session.add(user)
        db.session.commit()
        token = user.genereate_token()#生成token
        send_mail(subject='激活认证',recipients=['429859020@qq.com']
                  ,html='mail/send_mail.html',username=user.username,token=token)
        flash('邮件已发送')
        return redirect(url_for('user_bp.login'))
    return render_template('user/register.html',types=types)


#账户激活认证
@user_bp.route('/active/<token>')
def active(token):
    if User.active_token(token):
        flash('已完成账户认证')
        return redirect(url_for('user_bp.login'))
    else:
        flash('token有误')
        return redirect(url_for('user_bp.register'))



#登录
@user_bp.route('/login',methods=['GET','POST'])
def login():
    types = Article_type.query.all()
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        rember_me = request.form.get('rember_me')
        # 比对验证码是否正确
        if captcha != new_captcha:
            flash('验证码错误')
            return redirect(url_for('user_bp.register'))
        #验证用户名是否正确
        user = User.query.filter(User.username==username).first()
        if user:
            # 验证密码是否正确
            if check_password_hash(user.password,password):
                # 登录
                login_user(user, remember=rember_me)
                flash('登录成功')
                return redirect(url_for('user_bp.index'))
        flash('用户名或密码不存在')
        return redirect(url_for('user_bp.register'))
    return render_template('user/login.html',types=types)


#个人信息展示
@user_bp.route('/information_show')
@login_required
def information_show():
    types = Article_type.query.all()
    return render_template('user/information_show.html',types=types)


#修改个人信息
@user_bp.route('/information_modify',methods=['GET','POST'])
@login_required
def information_modify():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        phone = request.form.get('phone')
        user = User.query.get(current_user.id)
        user.username = username
        user.email = email
        user.phone = phone
        db.session.commit()
        flash('个人信息修改成功')
        return redirect(url_for('user_bp.index'))

    return redirect(url_for('user_bp.information_show'))


#退出
@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_bp.login'))



#密码修改
@user_bp.route('/password_modify',methods=['GET','POST'])
@login_required
def password_modify():
    types = Article_type.query.all()
    if request.method == 'POST':
        old_password = request.form.get('old_password')
        new_password = request.form.get('new_password')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        user = User.query.get(current_user.id)#得到一个用户对象
        if not check_password_hash(user.password,old_password):#密码比对
            flash('您输入的密码错误')
            return redirect(url_for('user_bp.password_modify'))
        elif captcha != new_captcha:
            flash('您输入的验证码错误')
            return redirect(url_for('user_bp.password_modify'))
        user.password = generate_password_hash(new_password)#把新密码写入数据库
        db.session.commit()
        flash('密码修改成功')
        return redirect(url_for('user_bp.index'))
    return render_template('user/password_modify.html',types=types)



#邮箱修改
@user_bp.route('/email_modify',methods=['GET','POST'])
@login_required
def email_modify():
    types = Article_type.query.all()
    if request.method == 'POST':
        old_email = request.form.get('old_email')
        new_email = request.form.get('new_email')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        user = User.query.filter(User.email==old_email).first()
        if not user:
            flash('用户不存在')
            return redirect(url_for('user_bp.email_modify'))
        elif captcha != new_captcha:
            flash('验证码错误')
            return redirect(url_for('user_bp.email_modify'))
        else:
            token = user.genereate_token()#生成token
            #发送激活邮件
            send_mail(subject='修改邮箱激活认证', recipients=['429859020@qq.com']
                      , html='mail/active_email.html', username=user.username,new_email=new_email,user_id=user.id, token=token)
            flash('邮件已发送')
            return redirect(url_for('user_bp.email_modify'))
    return render_template('user/email_modify.html',types=types)


#修改邮箱激活
@user_bp.route('/email_modify_active?<token>&new_email&user_id')
def email_modify_active(token):
    if User.active_token(token):
        new_email = request.args.get('new_email')
        user_id = request.args.get('user_id')
        user = User.query.get(user_id)
        if user:
            user.email = new_email
            db.session.commit()
            flash('邮箱修改成功')
            return redirect(url_for('user_bp.index'))
        else:
            flash('用户不存在')
            return redirect(url_for('user_bp.email_modify'))
    flash('token有误')
    return redirect(url_for('user_bp.email_modify'))



#头像上传及修改
@user_bp.route('/icon_modify',methods=['GET','POST'])
@login_required
def icon_modify():
    types = Article_type.query.all()
    if request.method == 'POST':
        icon = request.files.get('icon')
        suffix = '.'+icon.filename.rsplit('.',1)[1]#后缀名
        name = icon.filename.rsplit('.',1)[0] + str(random.randint(100,999))#拼接文件名
        filename = name + suffix
        photos.save(icon,name=filename)#保存本地文件
        user = User.query.get(current_user.id)#得到用户对象
        old_filename = os.path.join(Baseconfig.UPLOADED_PHOTOS_DEST,user.icon)#得到替换前的文件
        if old_filename != 'default.jpg':
            os.remove(old_filename)
        user.icon = filename#写进数据库
        db.session.commit()
        flash('头像更换成功')
        return render_template('user/icon_modify.html',types=types)
    return render_template('user/icon_modify.html',types=types)



#发布留言
@user_bp.route('/add_message',methods=['GET','POST'])
def add_message():
    if request.method == 'POST':
        name = request.form.get('name')
        email =request.form.get('email')
        phone =request.form.get('phone')
        content = request.form.get('content')
        message = Message()
        message.username = name
        message.content = content
        message.email = email
        message.phone = phone
        db.session.add(message)
        db.session.commit()
        flash('留言成功')
        return redirect(url_for('user_bp.index'))
    return render_template('message/add_message.html')


#展示留言
@user_bp.route('/show_message',methods=['GET','POST'])
@login_required
def show_message():
    types = Article_type.query.all()
    page = request.args.get('page',1,type=int)
    pagination = Message.query.order_by(Message.datetime.desc()).paginate(page=page,per_page=5,error_out=False)
    return render_template('message/del_message.html',pagination=pagination,types=types)

#删除留言
@user_bp.route('/del_message',methods=['GET','POST'])
@login_required
def del_message():
    mid = request.args.get('mid')
    message = Message.query.get(mid)
    if not message:
        flash('这条留言不存在')
        return redirect(url_for('user_bp.show_message'))
    db.session.delete(message)
    db.session.commit()
    flash('留言删除成功')
    return redirect(url_for('user_bp.show_message'))

#博主个人信息添加
@user_bp.route('/add_information',methods=['GET','POST'])
@login_required
def add_information():
    if request.method == 'POST':
        if Personal_information.query.first():
            flash('您的个人信息已添加，不能重复添加，如果您想修改可以进入修改页面')
            return redirect(url_for('user_bp.modify_information'))

templates/base.html
{% extends 'bootstrap/base.html' %}



{% block title %}
    基础模板
{% endblock %}
{# 导入jquery cdn #}
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


{% block styles %}
    {{ super() }}
    <style>
        .img-circle {
            border-radius: 50px;
            overflow: hidden;
            height: 25px;
            width: 25px;
        }

    </style>
{% endblock %}

{% block navbar %}
    <div class="container">
        <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="{{url_for('user_bp.index')}}">博客网站</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{{url_for('user_bp.show_information')}}">博主</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">文章<span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% for type in types %}
                    {% if not loop.last %}
                <li><a href="{{ url_for('article_bp.article_class_show',tid=type.id) }}">{{ type.type }}</a></li>
                <li role="separator" class="divider"></li>
                    {% else %}
                     <li><a href="{{ url_for('article_bp.article_class_show',tid=type.id) }}">{{ type.type }}</a></li>
                    {% endif %}
                {% endfor %}



              </ul>
            </li>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">相册<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('photo_bp.photo_upload') }}">图片上传</a></li>
                <li role="separator" class="divider"></li>
                  <li><a href="{{ url_for('photo_bp.my_photo') }}">我的相册</a></li>

              </ul>
            </li>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">留言<span class="caret"></span></a>
              <ul class="dropdown-menu">

                <li><a href="{{url_for('user_bp.add_message')}}">发布留言</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{url_for('user_bp.show_message')}}">管理留言</a></li>
              </ul>
            </li>

          </ul>
        {# 创建搜索表单 #}
          <form method="post" action="{{ url_for('article_bp.search') }}" class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" name="search" class="form-control" placeholder="请输入要搜索的关键词">
            </div>
            <button type="submit" class="btn btn-default" id="search">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('user_bp.logout') }}">退出</a></li>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{current_user.username}}<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('user_bp.information_show') }}">用户信息修改</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('user_bp.password_modify') }}">密码修改</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('user_bp.email_modify') }}">邮箱修改</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('user_bp.icon_modify') }}">头像修改</a></li>
                  <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('user_bp.add_information') }}">博主个人信息添加</a></li>
                  <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('user_bp.modify_information') }}">博主个人信息修改</a></li>
              </ul>
            </li>

          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">文章管理<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('article_bp.add_type') }}">添加文章类型</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('article_bp.show_type') }}">修改或删除文章类型</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('article_bp.publish') }}">发布文章</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('article_bp.show_user_article') }}">修改或删除文章</a></li>
                  <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('article_bp.show_comment') }}">管理评论</a></li>

              </ul>
            </li>
              {% else %}
            <li><a href="{{url_for('user_bp.register')}}">注册</a></li>
            <li><a href="{{url_for('user_bp.login')}}">登录</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    </div>

{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
    </div>
{% endfor %}
    </div>
    <br>
    {% block new_content %}
        <div class="container">
            新的内容
        </div>

    {% endblock %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% from 'macro/page_marco.html' import pagination_show %}
{% block title %}
首页
{% endblock %}

{% block new_content %}
    <div class="container">
        {% for article in pagination.items %}
            <div class="container">
                <p>
                <h3><label class="form-group">标题：</label>
                    <a href="{{ url_for('article_bp.details',aid=article.id) }}">{{ article.title }}</a></h3>
                <h4>
                    <label class="form-group">正文：</label>
                    {{ article.content }}
                </h4>
                <h5><label >新闻类型：</label>{{ article.article_type.type }}</h5>
                <h5><label >作者：</label>{{ article.user.username }}</h5>
                <h5><label >发布时间：</label>{{ article.datetime }}</h5>
                <br>

                </p>
            </div>


        {% endfor %}

{{ pagination_show(pagination,'user_bp.index') }}
</div>
{% endblock %}