apps/views/article.py
from flask import Blueprint, flash, request, redirect, render_template, url_for,jsonify
from flask_login import login_required,current_user
from sqlalchemy import and_, or_

from apps.models.ariticle import Article_type, Article, Comment, Like, Favorite
from exts import db
from exts.like import del_like, get_like, get_favorite, del_favorite

article_bp = Blueprint('article_bp',__name__,url_prefix='/article')#创建蓝图

#添加文章类型
@article_bp.route('/add_type',methods=['GET','POST'])
def add_type():
    types = Article_type.query.all()
    if request.method == 'POST':
        type = request.form.get('type')
        article_type = Article_type()
        article_type.type = type
        db.session.add(article_type)
        db.session.commit()
        flash('文章类型添加成功')
        return redirect(url_for('article_bp.show_type'))
    return render_template('article/add_type.html',types=types)


#修改文章类型
@article_bp.route('/modify_type',methods=['GET','POST'])
def modify_type():
    types = Article_type.query.all()
    if request.method == 'POST':
        tid = request.form.get('tid')
        type = request.form.get('type')
        article_type = Article_type.query.get(tid)
        article_type.type = type
        db.session.commit()
        flash('类型修改成功')
        return redirect(url_for('article_bp.show_type'))
    tid = request.args.get('tid')
    article_type = Article_type.query.get(tid)
    return render_template('article/modify_type.html',article_type=article_type,types=types)



#删除文章类型
@article_bp.route('/del_type',methods=['GET','POST'])
def del_type():
    tid = request.args.get('tid')
    article_type = Article_type.query.get(tid)
    db.session.delete(article_type)
    db.session.commit()
    flash('类型删除成功')
    return redirect(url_for('article_bp.show_type'))


#显示文章类型
@article_bp.route('show_type',methods=['GET','POST'])
def show_type():
    types= Article_type.query.all()
    return render_template('article/show_type.html',types=types)


#文章发布
@article_bp.route('/publish',methods=['GET','POST'])
@login_required
def publish():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        type_id = request.form.get('type_id')
        article = Article()
        article.title = title
        article.content = content
        article.type_id = type_id
        article.user_id = current_user.id
        db.session.add(article)
        db.session.commit()
        flash('文章发布成功')
        return redirect(url_for('user_bp.index'))
    types = Article_type.query.all()
    return render_template('article/publish_article.html',types=types)


#文章详情页
@article_bp.route('/details',methods=['GET','POST'])
def details():
    types = Article_type.query.all()
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id==aid).first()
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.filter(Comment.article_id == aid).order_by(Comment.datetime.desc()).paginate(page=page, per_page=5, error_out=False)
    return render_template('article/details.html',article=article,pagination=pagination,types=types)



#发布评论
@article_bp.route('/comment',methods=['GET','POST'])
@login_required
def comment():
    types = Article_type.query.all()
    aid = request.form.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    c_content = request.form.get('c_content')
    comment = Comment()
    comment.content = c_content
    comment.article_id = aid
    comment.user_id = current_user.id
    db.session.add(comment)
    db.session.commit()
    page = request.args.get('page',1,type=int)
    pagination = Comment.query.filter(Comment.article_id == aid).order_by(Comment.datetime.desc()).paginate(page=page,per_page=5,error_out=False)
    flash('评论成功')
    return render_template('article/details.html',article=article,pagination=pagination,types=types)



#点赞实现
@article_bp.route('/like',methods=['GET','POST'])
@login_required
def like():
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    if Like.is_like(aid):#判断是否已经点赞
        del_like(aid)#取消点赞
    else:
        get_like(aid)#增加点赞
    db.session.commit()
    return jsonify(num=article.like)



#收藏实现
@article_bp.route('/favorite',methods=['GET','POST'])
@login_required
def favorite():
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    if Favorite.is_favorite(aid):#判断是否已经收藏
        del_favorite(aid)#取消收藏
    else:
        get_favorite(aid)#增加收藏
    db.session.commit()
    return jsonify(num=article.Favorites)


#显示评论
@article_bp.route('/show_comment',methods=['GET','POST'])
@login_required
def show_comment():
    types = Article_type.query.all()
    page = request.args.get('page',1,type=int)
    pagination = Comment.query.filter(Comment.user_id==current_user.id)\
        .order_by(Comment.datetime.desc()).paginate(page=page,per_page=5,error_out=False)
    return render_template('comment/show_comment.html',pagination=pagination,types=types)


#删除评论
@article_bp.route('/del_comment/',methods=['GET','POST'])
@login_required
def del_comment_11():
    cid = request.args.get('cid')
    comment = Comment.query.filter(Comment.id==cid).first()
    if comment:
        db.session.delete(comment)
        db.session.commit()
        flash('评论删除成功')
    else:
        flash('该评论不存在')
    return redirect(url_for('article_bp.show_comment'))


#文章分类显示
@article_bp.route('/article_class_show/',methods=['GET','POST'])
@login_required
def article_class_show():
    types = Article_type.query.all()
    tid = request.args.get('tid')
    page = request.args.get('page',1,type=int)
    pagination = Article.query.filter(Article.type_id==tid).paginate(page=page,per_page=5,error_out=False)
    return render_template('article/article.html',pagination=pagination,types=types,tid=tid)


#显示当前用户的文章
@article_bp.route('/show_user_article/',methods=['GET','POST'])
@login_required
def show_user_article():
    types = Article_type.query.all()
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.filter(Article.user_id==current_user.id).paginate(page=page,per_page=5,error_out=False)
    return render_template('article/show_user_article.html',pagination=pagination,types=types)



#修改文章
@article_bp.route('/modify_article/',methods=['GET','POST'])
@login_required
def modify_article():
    if request.method == 'POST':
        aid = request.form.get('aid')
        title = request.form.get('title')
        content = request.form.get('content')
        article = Article.query.filter(Article.id==aid).first()
        article.title=title
        article.content=content
        db.session.commit()
        flash('文章修改成功')
        return redirect(url_for('article_bp.show_user_article'))
    types = Article_type.query.all()
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id==aid).first()
    return render_template('article/modify_article.html',article=article,types=types)

#删除文章
@article_bp.route('/del_article/',methods=['GET','POST'])
@login_required
def del_article():
    aid = request.args.get('aid')
    article = Article.query.filter(Article.id == aid).first()
    db.session.delete(article)
    db.session.commit()
    flash('文章删除成功')
    return redirect(url_for('article_bp.show_user_article'))


#通过关键词搜索文章
@article_bp.route('/search/',methods=['GET','POST'])
def search():
    types = Article_type.query.all()
    keyword = request.form.get('search')
    page = request.args.get('page',1,type=int)
    pagination = Article.query.filter(Article.title.contains(keyword)).paginate(page=page,per_page=5,error_out=False)
    if not pagination.items:
        flash('没有您要找的相关文章')
    return render_template('article/search_article.html', pagination=pagination, types=types)

templates/article/add_type.html
{% extends 'base.html' %}

{% block title %}
添加文章类型
{% endblock %}

{% block styles %}
{{ super() }}
{% endblock %}

{% block new_content %}
<div class="container">
    <form method="post" action="">
        <label class="form-group">类型</label>
        <input type="text" name="type" placeholder="请输入文章类型"><br>
        <br>
        <input type="submit" value="添加">
    </form>
</div>
{% endblock %}

templates/article/article.html
{% extends 'base.html' %}

{% block title %}
文章分类显示
{% endblock %}

{% block new_content %}
    <div class="container">
        {% for article in pagination.items %}
            <div class="container">
                <p>
                <h3><label class="form-group">标题：</label>
                    <a href="{{ url_for('article_bp.details',aid=article.id) }}">{{ article.title }}</a></h3>
                <h4>
                    <label class="form-group">正文：</label>
                    {{ article.content }}
                </h4>
                <h5><label >新闻类型：</label>{{ article.article_type.type }}</h5>
                <h5><label >作者：</label>{{ article.user.username }}</h5>
                <h5><label >发布时间：</label>{{ article.datetime }}</h5>
                <br>

                </p>
            </div>
        {% endfor %}
{% macro pagination_show(pagination,endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 如果没有上一页，则不显示。 #} {# 如果有上一页，则点击跳转到上一页的路由，否则显示#号 #}    {#向左箭头#}
            <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint,tid=tid,page=pagination.prev_num,**kwargs) }} {% else %}#{% endif %}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for p in pagination.iter_pages() %}{# 页码迭代器，自动生成页码 #}
                {% if p %}  {# 如果页码存在 #}
            {#中间页码部分#}
                    <li {% if pagination.page == p %} class="active" {% endif %}><a href="{{url_for(endpoint,tid=tid,page=p)}}">{{ p }}</a></li>
                    {# 点击当前页码跳转到当前页的路由 ,如果页码为当前页的时候为激活状态 #}
                {% else %}
                    <li><a>&hellip;</a></li>
                {% endif %}
            {% endfor %}
            {#向右箭头#}
            <li {% if not pagination.has_next %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for(endpoint,tid=tid,page=pagination.next_num,**kwargs) }}{% else %}#{% endif %}"
                        aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}
    {{ pagination_show(pagination,'article_bp.article_class_show') }}

</div>
{% endblock %}

templates/article/details.html
{% extends 'base.html' %}

{% block title %}
    文章详情页
{% endblock %}

{% block styles %}
{{ super() }}
    <style>
        #right{
            float: right;
        }
    </style>
{% endblock %}

{% block new_content %}
    <div class="container">
        <form method="post" action="{{ url_for('article_bp.comment') }}">
            <div class="container">
                <p>
                <h3><label class="form-group">标题：</label>
                    {{ article.title }}</h3>
                <h4>
                    <label class="form-group">正文：</label>
                    {{ article.content }}
                </h4>
                <h5><label>新闻类型：</label>{{ article.article_type.type }}</h5>
                <h5><label>作者：</label>{{ article.user.username }}</h5>
                <h5><label>发布时间：</label>{{ article.datetime }}</h5>
                <div id="right">
                    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">点赞</span><span tag="0">{{ article.like }}</span>&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true">收藏</span><span tag="0">{{ article.Favorites }}</span>

                </div>
                <br>


                <input type="hidden" name="aid" value="{{ article.id }}">
                <label>评论内容</label><br>
                <textarea name="c_content" class="form-control" style="width: 60%" rows="5" cols="60">写下你想说的，开始我们的对话
                    </textarea>
                <br>
                <input type="submit" value="发表评论">
                </p>

    </div>
        <br>
            <div>
                {% for comment in pagination.items %}
                    <h5>
                    <label><img class="img-circle" src="{{  "/static/upload/" + comment.user.icon  }}" alt="." style="width: 20px;height: 20px">&nbsp;&nbsp;{{ comment.user.username }}</label>
                    </h5>
                    <label>评论内容：</label>
                    {{ comment.content }}<br>
                    <label>评论时间：</label>
                    {{ comment.datetime }}<br>
                    <br>

                {% endfor %}

            </div>
    </form>
    {% macro pagination_show(pagination,endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 如果没有上一页，则不显示。 #} {# 如果有上一页，则点击跳转到上一页的路由，否则显示#号 #}    {#向左箭头#}
            <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint,aid=article.id,page=pagination.prev_num,**kwargs) }} {% else %}#{% endif %}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for p in pagination.iter_pages() %}{# 页码迭代器，自动生成页码 #}
                {% if p %}  {# 如果页码存在 #}
            {#中间页码部分#}
                    <li {% if pagination.page == p %} class="active" {% endif %}><a href="{{url_for(endpoint,aid=article.id,page=p)}}">{{ p }}</a></li>
                    {# 点击当前页码跳转到当前页的路由 ,如果页码为当前页的时候为激活状态 #}
                {% else %}
                    <li><a>&hellip;</a></li>
                {% endif %}
            {% endfor %}
            {#向右箭头#}
            <li {% if not pagination.has_next %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for(endpoint,aid=article.id,page=pagination.next_num,**kwargs) }}{% else %}#{% endif %}"
                        aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}
    {{ pagination_show(pagination,'article_bp.details') }}
    </div>
{% endblock %}



{#点击事件，传参到视图函数#}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            {# 点赞 #}
            $('.glyphicon-thumbs-up').click(function () {
                let $this=$(this);
                let tag=$this.next('span').attr('tag');{# 获取tag值 #}
                {# get方式传参 #}
                $.get("{{ url_for('article_bp.like') }}", {aid:{{article.id}}},function (data) {
                    $this.next('span').text(data.num);{# 接收数据 #}
                })
                if (tag == 0){
                    $this.css({'color':'red'})
                    $this.next('span').attr('tag',1){# 把tag变为1 #}
                } else {
                    $this.css({'color':'black'})
                    $this.next('span').attr('tag',0)
                }
            });

			{# 收藏 #}
            $('.glyphicon-heart-empty').click(function () {
                let $this=$(this);
                let tag=$this.next('span').attr('tag');{# 获取tag值 #}
                {# get方式传参 #}
                $.get("{{ url_for('article_bp.favorite') }}", {aid:{{article.id}}},function (data) {
                    $this.next('span').text(data.num);{# 接收数据 #}
                })
                if (tag == 0){
                    $this.css({'color':'red'})
                    $this.next('span').attr('tag',1){# 把tag变为1 #}
                } else {
                    $this.css({'color':'black'})
                    $this.next('span').attr('tag',0)
                }
            });
        });
    </script>
{% endblock %}

templates/article/modify_article.html
{% extends 'base.html' %}

{% block title %}
    修改文章
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block new_content %}
    <div class="container">
        <form method="post" action="{{ url_for('article_bp.modify_article') }}">
            <div>
                <input type="hidden" name="aid" value="{{ article.id }}">
                <label class="form-group">标题</label>
                <input type="text" name="title" value="{{ article.title }}"><br>
                <br>
            </div>
            <div>
                    <label class="form-group">类型</label>
                <select name="type_id" class="form-group">
                    <option value="0" >请选择文章分类</option>
                    {% for type in types %}
                        <option disabled value="{{ type.id }}">{{ type.type }}</option>
                    {% endfor %}
                </select>
            </div>
            <br>
            <br>
            <div>
                <label class="form-group">正文</label>
                <input type="text" name="content" value="{{ article.content }}" style="height: 200px;width: 500px"><br>
                <br>
            </div>

            <input type="submit" value="修改">
        </form>
    </div>
{% endblock %}

templates/article/modify_type.html
{% extends 'base.html' %}

{% block title %}
添加文章类型
{% endblock %}

{% block styles %}
{{ super() }}
{% endblock %}

{% block new_content %}
<div class="container">
    <form method="post" action="{{ url_for('article_bp.modify_type') }}">
        <input type="hidden" name="tid" value="{{ article_type.id }}">
        <label class="form-group">类型</label>
        <input type="text" name="type" value="{{ article_type.type }}"><br>
        <br>
        <input type="submit" value="修改">
    </form>
</div>
{% endblock %}

templates/article/publish_article.html
{% extends 'base.html' %}

{% block title %}
    发布文章
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block new_content %}
    <div class="container">
        <form method="post" action="">
            <div>
                <label class="form-group">标题</label>
                <input type="text" name="title" placeholder="请输入文章标题"><br>
                <br>
            </div>
            <div>
                    <label class="form-group">类型</label>
                <select name="type_id" class="form-group">
                    <option value="0">请选择文章分类</option>
                    {% for type in types %}
                        <option value="{{ type.id }}">{{ type.type }}</option>
                    {% endfor %}
                </select>
            </div>
            <br>
            <br>
            <div>
                <label class="form-group">正文</label>
                <input type="text" name="content" placeholder="请输入文章内容" style="height: 200px;width: 500px"><br>
                <br>
            </div>

            <input type="submit" value="提交">
        </form>
    </div>
{% endblock %}

templates/article/search_article.html
{% extends 'base.html' %}
{% from 'macro/page_marco.html' import pagination_show %}
{% block title %}
搜索文章
{% endblock %}

{% block new_content %}
    <div class="container">
        {% for article in pagination.items %}
            <div class="container">
                <p>
                <h3><label class="form-group">标题：</label>
                    <a href="{{ url_for('article_bp.details',aid=article.id) }}">{{ article.title }}</a></h3>
                <h4>
                    <label class="form-group">正文：</label>
                    {{ article.content }}
                </h4>
                <h5><label >新闻类型：</label>{{ article.article_type.type }}</h5>
                <h5><label >作者：</label>{{ article.user.username }}</h5>
                <h5><label >发布时间：</label>{{ article.datetime }}</h5>
                <br>

                </p>
            </div>


        {% endfor %}

{{ pagination_show(pagination,'article_bp.search') }}
</div>
{% endblock %}

templates/article/show_type.html
{% extends 'base.html' %}

{% block title %}
显示文章类型
{% endblock %}

{% block styles %}
{{ super() }}
{% endblock %}

{% block new_content %}
<div class="container">
    <h4>文章类型：</h4><br>
<div class="form-group">
    {% for type in types %}
        <h3>
        {{ type.id }}. {{ type.type }}&nbsp;&nbsp;<button class="btn btn-info btn-xs type_modify" tag="{{ type.id }}">修改</button>&nbsp;&nbsp;<button class="btn btn-info btn-xs type_del" tag2="{{ type.id }}">删除</button><br>
        <br>
        </h3>
    {% endfor %}
</div>




</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='js/modify_article_type.js') }}"></script>
    <script src="{{ url_for('static',filename='js/del_article_type.js') }}"></script>
{% endblock %}

templates/article/show_user_article.html
{% extends 'base.html' %}

{% block title %}
文章分类显示
{% endblock %}

{% block new_content %}
    <div class="container">
        {% for article in pagination.items %}
            <div class="container">
                <p>
                <h3><label class="form-group">标题：</label>
                    <a href="{{ url_for('article_bp.details',aid=article.id) }}">{{ article.title }}</a></h3>
                <h4>
                    <label class="form-group">正文：</label>
                    {{ article.content }}
                </h4>
                <h5><label >新闻类型：</label>{{ article.article_type.type }}</h5>
                <h5><label >作者：</label>{{ article.user.username }}</h5>
                <h5><label >发布时间：</label>{{ article.datetime }}</h5>
                <button class="btn btn-info btn-xs article_modify" tag="{{ article.id }}">修改</button>&nbsp;&nbsp;<button class="btn btn-info btn-xs article_del" tag2="{{ article.id }}">删除</button><br>
                <br>
                </p>
            </div>
        {% endfor %}
{% macro pagination_show(pagination,endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 如果没有上一页，则不显示。 #} {# 如果有上一页，则点击跳转到上一页的路由，否则显示#号 #}    {#向左箭头#}
            <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint,page=pagination.prev_num,**kwargs) }} {% else %}#{% endif %}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for p in pagination.iter_pages() %}{# 页码迭代器，自动生成页码 #}
                {% if p %}  {# 如果页码存在 #}
            {#中间页码部分#}
                    <li {% if pagination.page == p %} class="active" {% endif %}><a href="{{url_for(endpoint,page=p)}}">{{ p }}</a></li>
                    {# 点击当前页码跳转到当前页的路由 ,如果页码为当前页的时候为激活状态 #}
                {% else %}
                    <li><a>&hellip;</a></li>
                {% endif %}
            {% endfor %}
            {#向右箭头#}
            <li {% if not pagination.has_next %} class="disabled" {% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for(endpoint,page=pagination.next_num,**kwargs) }}{% else %}#{% endif %}"
                        aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}
    {{ pagination_show(pagination,'article_bp.show_user_article') }}

</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='js/modify_article.js') }}"></script>
    <script src="{{ url_for('static',filename='js/del_article.js') }}"></script>
{% endblock %}