apps/models/user.py
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from sqlalchemy.orm import backref

from config import Baseconfig
from exts import db, loginmanager
from datetime import datetime


class User(UserMixin,db.Model):
    id = db.Column(db.INTEGER,primary_key=True,autoincrement=True)
    username = db.Column(db.String(20),nullable=False)
    password = db.Column(db.String(128),nullable=False)
    email = db.Column(db.String(50),nullable=False)
    phone = db.Column(db.String(11),nullable=False)
    icon = db.Column(db.String(50),default='static/upload/default.jpg')
    activation = db.Column(db.Boolean,default=0)
    state = db.Column(db.Boolean,default=1)
    datetime = db.Column(db.DateTime,default=datetime.now)
    photo = db.relationship('Photo', backref='user',lazy='dynamic')
    article = db.relationship('Article', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')
    likes = db.relationship('Like', backref='user', lazy='dynamic')
    favorite = db.relationship('Favorite', backref='user', lazy='dynamic')


    def __str__(self):
        return self.username


    #生成token
    def genereate_token(self):
        s = Serializer(Baseconfig.SECRET_KEY,expires_in=3600)
        token = s.dumps({'id':self.id})#把字典转化为字符串
        return token

    #激活token
    @staticmethod
    def active_token(token):
        s = Serializer(Baseconfig.SECRET_KEY)
        try:
            data = s.loads(token)#把字符串转化为字典
        except:
            return False
        #更改激活状态为True
        user = User.query.get(data.get('id'))
        user.activation = True
        db.session.commit()
        return True

#回调函数
@loginmanager.user_loader
def loader_user(user_id):
    return User.query.get(int(user_id))



#博主个人信息表
class Personal_information(db.Model):
    id = db.Column(db.INTEGER, primary_key=True, autoincrement=True)
    content = db.Column(db.Text,nullable=False)

apps/views/user.py
import os
import random
from io import BytesIO


from flask_login import login_user,current_user,logout_user,login_required
from flask import Blueprint, render_template, request, flash, make_response, redirect, url_for

from werkzeug.security import generate_password_hash, check_password_hash

from apps.models.ariticle import Article, Article_type, Message
from apps.models.user import User, Personal_information
from config import Baseconfig
from exts import db, cache, photos
from exts.captcha import generate_captcha
from exts.mail_send import send_mail

user_bp = Blueprint('user_bp',__name__,url_prefix='/user')#创建蓝图


#首页
@user_bp.route('/index')
def index():
    types = Article_type.query.all()
    page = request.args.get('page',1,type=int)
    pagination = Article.query.paginate(page=page,per_page=5,error_out=False)
    return render_template('index.html',pagination=pagination,types=types)


#把验证码返回到前端页面
@user_bp.route('/captcha_show')
def captcha_show():
    im,code = generate_captcha(4)
    cache.set('cc',code,timeout=180)#把code存入redis
    buffer = BytesIO()#创建缓存对象,以二进制的形式存储
    im.save(buffer,'JPEG')#存入缓存
    image = buffer.getvalue()#得到图片
    response = make_response(image)#自定义response
    response.headers['Content-Type'] = 'image/jpg'#设置响应头
    return response


#注册
@user_bp.route('/register',methods=['GET','POST'])
def register():
    types = Article_type.query.all()
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        email = request.form.get('email')
        phone = request.form.get('phone')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        if password != repassword:
            flash('您输入的两次密码不一致')
            return redirect(url_for('user_bp.register'))
        if captcha != new_captcha:
            flash('您输入的验证码有误')
            return redirect(url_for('user_bp.register'))
        #把数据写入数据库
        user = User()
        user.username = username
        user.password = generate_password_hash(password)
        user.email = email
        user.phone = phone
        db.session.add(user)
        db.session.commit()
        token = user.genereate_token()#生成token
        send_mail(subject='激活认证',recipients=['429859020@qq.com']
                  ,html='mail/send_mail.html',username=user.username,token=token)
        flash('邮件已发送')
        return redirect(url_for('user_bp.login'))
    return render_template('user/register.html',types=types)


#账户激活认证
@user_bp.route('/active/<token>')
def active(token):
    if User.active_token(token):
        flash('已完成账户认证')
        return redirect(url_for('user_bp.login'))
    else:
        flash('token有误')
        return redirect(url_for('user_bp.register'))



#登录
@user_bp.route('/login',methods=['GET','POST'])
def login():
    types = Article_type.query.all()
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        rember_me = request.form.get('rember_me')
        # 比对验证码是否正确
        if captcha != new_captcha:
            flash('验证码错误')
            return redirect(url_for('user_bp.register'))
        #验证用户名是否正确
        user = User.query.filter(User.username==username).first()
        if user:
            # 验证密码是否正确
            if check_password_hash(user.password,password):
                # 登录
                login_user(user, remember=rember_me)
                flash('登录成功')
                return redirect(url_for('user_bp.index'))
        flash('用户名或密码不存在')
        return redirect(url_for('user_bp.register'))
    return render_template('user/login.html',types=types)


#个人信息展示
@user_bp.route('/information_show')
@login_required
def information_show():
    types = Article_type.query.all()
    return render_template('user/information_show.html',types=types)


#修改个人信息
@user_bp.route('/information_modify',methods=['GET','POST'])
@login_required
def information_modify():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        phone = request.form.get('phone')
        user = User.query.get(current_user.id)
        user.username = username
        user.email = email
        user.phone = phone
        db.session.commit()
        flash('个人信息修改成功')
        return redirect(url_for('user_bp.index'))

    return redirect(url_for('user_bp.information_show'))


#退出
@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_bp.login'))



#密码修改
@user_bp.route('/password_modify',methods=['GET','POST'])
@login_required
def password_modify():
    types = Article_type.query.all()
    if request.method == 'POST':
        old_password = request.form.get('old_password')
        new_password = request.form.get('new_password')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        user = User.query.get(current_user.id)#得到一个用户对象
        if not check_password_hash(user.password,old_password):#密码比对
            flash('您输入的密码错误')
            return redirect(url_for('user_bp.password_modify'))
        elif captcha != new_captcha:
            flash('您输入的验证码错误')
            return redirect(url_for('user_bp.password_modify'))
        user.password = generate_password_hash(new_password)#把新密码写入数据库
        db.session.commit()
        flash('密码修改成功')
        return redirect(url_for('user_bp.index'))
    return render_template('user/password_modify.html',types=types)



#邮箱修改
@user_bp.route('/email_modify',methods=['GET','POST'])
@login_required
def email_modify():
    types = Article_type.query.all()
    if request.method == 'POST':
        old_email = request.form.get('old_email')
        new_email = request.form.get('new_email')
        captcha = request.form.get('captcha')
        new_captcha = cache.get('cc')
        user = User.query.filter(User.email==old_email).first()
        if not user:
            flash('用户不存在')
            return redirect(url_for('user_bp.email_modify'))
        elif captcha != new_captcha:
            flash('验证码错误')
            return redirect(url_for('user_bp.email_modify'))
        else:
            token = user.genereate_token()#生成token
            #发送激活邮件
            send_mail(subject='修改邮箱激活认证', recipients=['429859020@qq.com']
                      , html='mail/active_email.html', username=user.username,new_email=new_email,user_id=user.id, token=token)
            flash('邮件已发送')
            return redirect(url_for('user_bp.email_modify'))
    return render_template('user/email_modify.html',types=types)


#修改邮箱激活
@user_bp.route('/email_modify_active?<token>&new_email&user_id')
def email_modify_active(token):
    if User.active_token(token):
        new_email = request.args.get('new_email')
        user_id = request.args.get('user_id')
        user = User.query.get(user_id)
        if user:
            user.email = new_email
            db.session.commit()
            flash('邮箱修改成功')
            return redirect(url_for('user_bp.index'))
        else:
            flash('用户不存在')
            return redirect(url_for('user_bp.email_modify'))
    flash('token有误')
    return redirect(url_for('user_bp.email_modify'))



#头像上传及修改
@user_bp.route('/icon_modify',methods=['GET','POST'])
@login_required
def icon_modify():
    types = Article_type.query.all()
    if request.method == 'POST':
        icon = request.files.get('icon')
        suffix = '.'+icon.filename.rsplit('.',1)[1]#后缀名
        name = icon.filename.rsplit('.',1)[0] + str(random.randint(100,999))#拼接文件名
        filename = name + suffix
        photos.save(icon,name=filename)#保存本地文件
        user = User.query.get(current_user.id)#得到用户对象
        old_filename = os.path.join(Baseconfig.UPLOADED_PHOTOS_DEST,user.icon)#得到替换前的文件
        if old_filename != 'default.jpg':
            os.remove(old_filename)
        user.icon = filename#写进数据库
        db.session.commit()
        flash('头像更换成功')
        return render_template('user/icon_modify.html',types=types)
    return render_template('user/icon_modify.html',types=types)



#发布留言
@user_bp.route('/add_message',methods=['GET','POST'])
def add_message():
    if request.method == 'POST':
        name = request.form.get('name')
        email =request.form.get('email')
        phone =request.form.get('phone')
        content = request.form.get('content')
        message = Message()
        message.username = name
        message.content = content
        message.email = email
        message.phone = phone
        db.session.add(message)
        db.session.commit()
        flash('留言成功')
        return redirect(url_for('user_bp.index'))
    return render_template('message/add_message.html')


#展示留言
@user_bp.route('/show_message',methods=['GET','POST'])
@login_required
def show_message():
    types = Article_type.query.all()
    page = request.args.get('page',1,type=int)
    pagination = Message.query.order_by(Message.datetime.desc()).paginate(page=page,per_page=5,error_out=False)
    return render_template('message/del_message.html',pagination=pagination,types=types)

#删除留言
@user_bp.route('/del_message',methods=['GET','POST'])
@login_required
def del_message():
    mid = request.args.get('mid')
    message = Message.query.get(mid)
    if not message:
        flash('这条留言不存在')
        return redirect(url_for('user_bp.show_message'))
    db.session.delete(message)
    db.session.commit()
    flash('留言删除成功')
    return redirect(url_for('user_bp.show_message'))

#博主个人信息添加
@user_bp.route('/add_information',methods=['GET','POST'])
@login_required
def add_information():
    if request.method == 'POST':
        if Personal_information.query.first():
            flash('您的个人信息已添加，不能重复添加，如果您想修改可以进入修改页面')
            return redirect(url_for('user_bp.modify_information'))

templates/user/email_modify.html
{% extends 'base.html' %}

{% block title %}
    邮箱修改
{% endblock %}

{% block new_content %}
<div class="container">
    <form method="post" action="{{ url_for('user_bp.email_modify') }}" class="form-horizontal">
  <div class="form-group">
    <label  class="col-sm-2 control-label">旧邮箱</label>
    <div class="col-sm-10">
      <input type="text" name="old_email" class="form-control" placeholder="请输入旧邮箱">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">新邮箱</label>
    <div class="col-sm-10">
      <input type="text" name="new_email" class="form-control"  placeholder="请输入新邮箱">
    </div>
  </div>

  <div class="form-group">
    <label for="inputcaptcha" class="col-sm-2 control-label">验证码</label>
    <div class="col-sm-10">
      <input type="text" name="captcha" class="form-control" id="inputcaptcha" placeholder="请输入验证码"><br>
        <span><img id="img" src="{{ url_for('user_bp.captcha_show') }}" alt="."></span>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">修改</button>
    </div>
  </div>
</form>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#img').click(function () {
            $(this).attr('src', "{{ url_for('user_bp.captcha_show') }}?ran=" + Math.random())
        })
    </script>
{% endblock %}

templates/user/forget_password.html
{% extends 'base.html' %}

{% block title %}
    忘记密码
{% endblock %}


{% block new_content %}
    <div class="container">
        <form method="post" action="" class="form-horizontal">
            <div class="form-group">
                <label for="inputusername" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" name="username" class="form-control" id="inputusername" placeholder="请输入用户名">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-10">
                    <input type="text" name="captcha" class="form-control" id="inputPassword3" placeholder="请输入验证码"><br>
                    <span><img id="img"
                               src="{{ url_for('user_bp.captcha_show') }}"#}
                               alt="."></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">确定</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#img').click(function () {
            $(this).attr('src', "{{ url_for('user_bp.captcha_show') }}?ran=" + Math.random())
        })
    </script>
{% endblock %}

templates/user/icon_modify.html
{% extends 'base.html' %}

{% block title %}
头像上传修改
{% endblock %}

{% block new_content %}
    <div class="container">
        <form method="post" action="" enctype="multipart/form-data">
            <label class="form-group">头像上传</label>
            <input type="file" class="form-group" name="icon" >
            <input type="submit" value="上传"><br>
            <br>
            <label class="form-group">头像</label>
            <img class="img-circle" src="{{ "/static/upload/" + current_user.icon }}" alt="." style="width: 64px;height: 64px" >
        </form>
    </div>
{% endblock %}

templates/user/information_show.html
{% extends 'base.html' %}

{% block title %}
    个人信息展示
{% endblock %}


{% block new_content %}
    <div class="container">
        <form method="post" action="{{ url_for('user_bp.information_modify') }}" class="form-horizontal">

            <div class="form-group">
                <label for="inputusername" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" name="username" class="form-control" id="inputusername" value="{{ current_user.username }}">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3"  class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password"  name="password" class="form-control" id="inputPassword3" value="{{ current_user.password }}"  disabled="" >
                </div>
            </div>

            <div class="form-group">
                <label for="inputemail" class="col-sm-2 control-label">邮箱</label>
                <div class="col-sm-10">
                    <input type="email" name="email" class="form-control" id="inputemail" value="{{ current_user.email }}">
                </div>
            </div>
            <div class="form-group">
                <label for="inputphone" class="col-sm-2 control-label">手机号</label>
                <div class="col-sm-10">
                    <input type="text" name="phone" class="form-control" id="inputtext" value="{{ current_user.phone }}">
                </div>
            </div>



            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">修改</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %}
    登录页面
{% endblock %}


{% block new_content %}
<div class="container">
    <form method="post" action="{{ url_for('user_bp.login') }}" class="form-horizontal">
  <div class="form-group">
    <label for="inputusername"  class="col-sm-2 control-label">用户名</label>
    <div class="col-sm-10">
      <input type="text" name="username" class="form-control" id="inputusername" placeholder="请输入用户名">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
    <div class="col-sm-10">
      <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="请输入密码">
    </div>
  </div>

  <div class="form-group">
    <label for="inputcaptcha" class="col-sm-2 control-label">验证码</label>
    <div class="col-sm-10">
      <input type="text" name="captcha" class="form-control" id="inputcaptcha" placeholder="请输入验证码"><br>
        <span><img id="img" src="{{ url_for('user_bp.captcha_show') }}" alt="."></span>
        <br>
        &nbsp;&nbsp;&nbsp;<h4><a href="{{ url_for('user_bp.register') }}">注册账号</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{ url_for('user_bp.forget_password') }}">忘记密码</a></h4>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox" name="rember_me"> 记住我
        </label>

      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">登录</button>
    </div>

  </div>
</form>



</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#img').click(function () {
            $(this).attr('src', "{{ url_for('user_bp.captcha_show') }}?ran=" + Math.random())
        })
    </script>
{% endblock %}

templates/user/password_modify.html
{% extends 'base.html' %}

{% block title %}
    密码修改
{% endblock %}

{% block new_content %}
<div class="container">
    <form method="post" action="{{ url_for('user_bp.password_modify') }}" class="form-horizontal">
  <div class="form-group">
    <label  class="col-sm-2 control-label">旧密码</label>
    <div class="col-sm-10">
      <input type="password" name="old_password" class="form-control" placeholder="请输入旧密码">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">新密码</label>
    <div class="col-sm-10">
      <input type="password" name="new_password" class="form-control"  placeholder="请输入新密码">
    </div>
  </div>

  <div class="form-group">
    <label for="inputcaptcha" class="col-sm-2 control-label">验证码</label>
    <div class="col-sm-10">
      <input type="text" name="captcha" class="form-control" id="inputcaptcha" placeholder="请输入验证码"><br>
        <span><img id="img" src="{{ url_for('user_bp.captcha_show') }}" alt="."></span>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">修改</button>
    </div>
  </div>
</form>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#img').click(function () {
            $(this).attr('src', "{{ url_for('user_bp.captcha_show') }}?ran=" + Math.random())
        })
    </script>
{% endblock %}

templates/user/personal_information_add.html
{% extends 'base.html' %}

{% block title %}
    博主个人信息添加
{% endblock %}


{% block new_content %}
    <div class="container">
        <form method="post" action="{{ url_for('user_bp.add_information') }}" class="form-horizontal">

            <div class="form-group">
                <label  class="col-sm-2 control-label">个人信息</label>
                <div class="col-sm-10">
                    <input type="text" name="content" class="form-control" placeholder="请输入博主个人信息" style="height:100px;width: 500px">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">添加</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/user/personal_information_modify.html
{% extends 'base.html' %}

{% block title %}
    博主个人信息添加
{% endblock %}

information
{% block new_content %}
    <div class="container">
        <form method="post" action="{{ url_for('user_bp.modify_information') }}" class="form-horizontal">

            <div class="form-group">
                <label  class="col-sm-2 control-label">个人信息</label>
                <div class="col-sm-10">
                    <input type="text" name="content" class="form-control" value="{{ personal_information.content }}" style="height:100px;width: 500px">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">修改</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/user/personal_information_show.html
{% extends 'base.html' %}

{% block title %}
    博主个人信息展示
{% endblock %}


{% block new_content %}
    <div class="container">

            <div class="container">
                <p>
                <h4>
                    <label class="form-group">个人信息</label>
                    {{ personal_information.content }}
                </h4>
                </p>
            </div>

    </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block title %}
    注册页面
{% endblock %}


{% block new_content %}
    <div class="container">
        <form method="post" action="" class="form-horizontal">
            <div class="form-group">
                <label for="inputusername" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" name="username" class="form-control" id="inputusername" placeholder="请输入用户名">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3"  class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password"  name="password" class="form-control" id="inputPassword3" placeholder="请输入密码">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password" name="repassword" class="form-control" id="inputPassword3" placeholder="请再次输入密码">
                </div>
            </div>
            <div class="form-group">
                <label for="inputemail" class="col-sm-2 control-label">邮箱</label>
                <div class="col-sm-10">
                    <input type="email" name="email" class="form-control" id="inputemail" placeholder="请输入邮箱">
                </div>
            </div>
            <div class="form-group">
                <label for="inputphone" class="col-sm-2 control-label">手机号</label>
                <div class="col-sm-10">
                    <input type="text" name="phone" class="form-control" id="inputtext" placeholder="请输入手机号">
                </div>
            </div>

            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-10">
                    <input type="text" name="captcha" class="form-control" id="inputPassword3" placeholder="请输入验证码"><br>
                    <span><img id="img"
                               src="{{ url_for('user_bp.captcha_show') }}"#}
                               alt="."></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">注册</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#img').click(function () {
            $(this).attr('src', "{{ url_for('user_bp.captcha_show') }}?ran=" + Math.random())
        })
    </script>
{% endblock %}

templates/user/set_password.html
{% extends 'base.html' %}

{% block title %}
    设置密码
{% endblock %}


{% block new_content %}
    <div class="container">
        <form method="post" action="{{ url_for('user_bp.set_password') }}" class="form-horizontal">
            <input type="hidden" name="username" value="{{ username }}">
            <div class="form-group">
                <label for="inputPassword3"  class="col-sm-2 control-label">旧密码</label>
                <div class="col-sm-10">
                    <input type="password"  name="old_password" class="form-control"  placeholder="请输入旧密码">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">新密码</label>
                <div class="col-sm-10">
                    <input type="password" name="new_password" class="form-control"  placeholder="请输入新密码">
                </div>
            </div>



            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">修改</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}